services:
  postgres:
    image: postgres:16
    container_name: mes-db
    environment:
      POSTGRES_DB: mes_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - mes_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d mes_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  mes_db_data: